name: TheRiftCore
version: '${project.version}'
main: com.therift.theriftcore.TheRiftCore
api-version: 1.19
authors: [ TheRiftt ]
description: The Core Plugin for the RiftNetWork
depend: [LuckPerms]
commands:
  allPlayers:
    permission: "therift.allplayers"
  spawn:
  resetdata:
    permission: "therift.resetdata"
  verify:
  staff:
    permission: "therift.staff"
  unban:
    permission: "therift.unban"
  report:
  ban:
    permission: "therift.ban"
  warn:
    permission: "therift.warn"
  kick:
    permission: "therift.kick"
  mute:
    permission: "therift.mute"
  pardon:
    permission: "therift.unban"
  chatmute:
    permission: "therift.chatmute"

