name: TheRiftCore
version: '${project.version}'
main: com.therift.theriftcore.Main
api-version: 1.19
authors: [ TheRiftt ]
description: The Core Plugin for the RiftNetWork
commands:
  allPlayers:
    permission: "therift.allplayers"
  spawn:
  resetdata:
    permission: "therift.resetdata"
  verify:
